theme: minima
title: Zach's Personal Website

author: Zach Russell
email: zacharyrussell01@gmail.com

bio: Software Engineer
github_username: Zach-Russell
linkedin: "zachary-russell-350453207"
show_excerpts: true
