theme: minima
title: Zach's Personal Website
pages:
    - title: About Me
      path: /Zach's Personal Website/AboutMe.md


author: Zach Russell
email: zacharyrussell01@gmail.com

bio: Software Engineer
github_username: Zach-Russell
linkedin_username: zachary-russell-350453207
show_excerpts: true
