theme: minima

#Title
name: Zach's Website


#Navigation
navigation:
- text: Introduction
  internal: true
  url: ./
- text: Add a new page
  internal: true
  url: add-a-new-page
- text: Configure the Guide
  internal: true
  url: configure-the-guide
- text: GitHub Setup
  internal: true
  url: github
- text: Create a Glossary
  glossary: true
- text: Edit this Repo
